  maximum:
    length_email: 255
    length_name: 50
  minimum:
    length_pass: 6
  users:
    size_page: 50
    size_image: 60
    per_page: 10
  time_limit: 2
  max_content: 140
  size_pic: 5
  resize_max: 400
  max_user: 50
